In [1]:
#preprocesory
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import Binarizer

import pandas as pd

In [2]:
from sklearn import datasets
iris = datasets.load_iris()

#iris.data
iris.feature_names




['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [3]:
scaler = StandardScaler()
scaler.fit(iris.data)
newdata = scaler.transform(iris.data)
newdata

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [4]:
scaler2 = Binarizer()
scaler2.fit(newdata)
newdata2=scaler2.transform(newdata)
newdata2

array([[0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],


In [5]:
from sklearn.pipeline import Pipeline


pipe=Pipeline([('std',StandardScaler()),('bin',Binarizer())])
pipe.fit(iris.data)
newdata3=pipe.transform(iris.data)

newdata3

array([[0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],


In [6]:
from sklearn.compose import ColumnTransformer



ct= ColumnTransformer([('std',StandardScaler(),[0]),('x','passthrough',[0]),('minmax',MinMaxScaler(feature_range=(5,10)),[2])])
ct.fit(iris.data)
res_ct=ct.transform(iris.data)


res_ct


array([[-0.90068117,  5.1       ,  5.33898305],
       [-1.14301691,  4.9       ,  5.33898305],
       [-1.38535265,  4.7       ,  5.25423729],
       [-1.50652052,  4.6       ,  5.42372881],
       [-1.02184904,  5.        ,  5.33898305],
       [-0.53717756,  5.4       ,  5.59322034],
       [-1.50652052,  4.6       ,  5.33898305],
       [-1.02184904,  5.        ,  5.42372881],
       [-1.74885626,  4.4       ,  5.33898305],
       [-1.14301691,  4.9       ,  5.42372881],
       [-0.53717756,  5.4       ,  5.42372881],
       [-1.26418478,  4.8       ,  5.50847458],
       [-1.26418478,  4.8       ,  5.33898305],
       [-1.87002413,  4.3       ,  5.08474576],
       [-0.05250608,  5.8       ,  5.16949153],
       [-0.17367395,  5.7       ,  5.42372881],
       [-0.53717756,  5.4       ,  5.25423729],
       [-0.90068117,  5.1       ,  5.33898305],
       [-0.17367395,  5.7       ,  5.59322034],
       [-0.90068117,  5.1       ,  5.42372881],
       [-0.53717756,  5.4       ,  5.593

In [7]:
pipe2=Pipeline([('ct',ct),('bin',Binarizer())])

pipe2.fit(iris.data)
res_pipe2=pipe2.transform(iris.data)
res_pipe2

array([[0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1

In [8]:
from sklearn.decomposition import PCA
import numpy as np
pipe3=Pipeline([('std',StandardScaler()),('pca',PCA(n_components=4))])

pipe3.fit(iris.data)
res_pipe3=pipe3.transform(iris.data)
res_pipe3


array([[-2.26470281e+00,  4.80026597e-01, -1.27706022e-01,
        -2.41682039e-02],
       [-2.08096115e+00, -6.74133557e-01, -2.34608854e-01,
        -1.03006775e-01],
       [-2.36422905e+00, -3.41908024e-01,  4.42014848e-02,
        -2.83770534e-02],
       [-2.29938422e+00, -5.97394508e-01,  9.12901063e-02,
         6.59555596e-02],
       [-2.38984217e+00,  6.46835383e-01,  1.57381957e-02,
         3.59228133e-02],
       [-2.07563095e+00,  1.48917752e+00,  2.69682944e-02,
        -6.60818022e-03],
       [-2.44402884e+00,  4.76441976e-02,  3.35470401e-01,
         3.67755572e-02],
       [-2.23284716e+00,  2.23148073e-01, -8.86954979e-02,
         2.46120962e-02],
       [-2.33464048e+00, -1.11532768e+00,  1.45076864e-01,
         2.68592208e-02],
       [-2.18432817e+00, -4.69013561e-01, -2.53765567e-01,
         3.98992877e-02],
       [-2.16631010e+00,  1.04369065e+00, -2.68681102e-01,
        -1.67313672e-02],
       [-2.32613087e+00,  1.33078335e-01,  9.37592444e-02,
      

In [9]:
np.var(res_pipe3,axis=0)

array([2.91849782, 0.91403047, 0.14675688, 0.02071484])

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier 
X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.2,random_state=0)

pipe4=Pipeline([('ct',ct),('std',StandardScaler()),('pca',PCA(n_components=3)),('tree',DecisionTreeClassifier())])

pipe4.fit(X_train,y_train)
res=pipe4.predict(X_train)
np.transpose(np.array([y_train,res]))




array([[2, 2],
       [1, 1],
       [0, 0],
       [2, 2],
       [2, 2],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [2, 2],
       [0, 0],
       [2, 2],
       [0, 0],
       [0, 0],
       [1, 1],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [1, 1],
       [2, 2],
       [1, 1],
       [1, 1],
       [2, 1],
       [2, 2],
       [2, 2],
       [2, 2],
       [1, 1],
       [2, 2],
       [1, 1],
       [0, 0],
       [2, 2],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [2, 2],
       [0, 0],
       [0, 0],
       [2, 2],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [2, 2],
       [1, 1],
       [0, 0],
       [1, 1],
       [2, 2],
       [1, 1],
       [0, 0],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [0, 0],
       [0, 0],
       [2, 2],
       [2, 2],
       [0, 0],
       [2, 2],
       [0, 0],
       [2, 2],
       [2, 2],
       [0,

In [11]:
pipe4.score(X_test,y_test)

0.9

In [13]:
pipe4.set_params(pca__n_components=2)
print(pipe4)
pipe4.fit(X_train,y_train)
pipe4.score(X_test,y_test)

Pipeline(steps=[('ct',
                 ColumnTransformer(transformers=[('std', StandardScaler(), [0]),
                                                 ('x', 'passthrough', [0]),
                                                 ('minmax',
                                                  MinMaxScaler(feature_range=(5,
                                                                              10)),
                                                  [2])])),
                ('std', StandardScaler()), ('pca', PCA(n_components=2)),
                ('tree', DecisionTreeClassifier())])


0.9

In [ ]:
from sklearn.model_selection import cross_val_score
scores=cross_val_score(pipe4,X_train,y_train,cv=10)

In [ ]:
print(f"Średnia {scores.mean()}, odchylenie standardowe {scores.std()}")

Średnia 0.9, odchylenie standardowe 0.07264831572567788
