In [17]:
#preprocesory
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import Binarizer
from sklearn.preprocessing import Normalizer

import pandas as pd

In [2]:
from sklearn import datasets
iris = datasets.load_iris()

print(iris.data)
print(type(iris.data))
print(type(iris))
iris.feature_names


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [3]:
scaler = StandardScaler()
scaler.fit(iris.data)
newdata = scaler.transform(iris.data)
newdata

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [4]:
scaler2 = Binarizer()
scaler2.fit(newdata)
newdata2=scaler2.transform(newdata)
newdata2

array([[0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],


In [5]:
from sklearn.pipeline import Pipeline


pipe=Pipeline([('std',StandardScaler()),('bin',Binarizer())])
pipe.fit(iris.data)
newdata3=pipe.transform(iris.data)

print(Pipeline)

newdata3

<class 'sklearn.pipeline.Pipeline'>


array([[0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],


In [6]:
from sklearn.compose import ColumnTransformer

ct= ColumnTransformer([('std',StandardScaler(),[0]),('minmax',MinMaxScaler(feature_range=(5,10)),[2])], remainder="passthrough")

ct.fit(iris.data)
res_ct=ct.transform(iris.data)

res_ct

array([[-0.90068117,  5.33898305,  3.5       ,  0.2       ],
       [-1.14301691,  5.33898305,  3.        ,  0.2       ],
       [-1.38535265,  5.25423729,  3.2       ,  0.2       ],
       [-1.50652052,  5.42372881,  3.1       ,  0.2       ],
       [-1.02184904,  5.33898305,  3.6       ,  0.2       ],
       [-0.53717756,  5.59322034,  3.9       ,  0.4       ],
       [-1.50652052,  5.33898305,  3.4       ,  0.3       ],
       [-1.02184904,  5.42372881,  3.4       ,  0.2       ],
       [-1.74885626,  5.33898305,  2.9       ,  0.2       ],
       [-1.14301691,  5.42372881,  3.1       ,  0.1       ],
       [-0.53717756,  5.42372881,  3.7       ,  0.2       ],
       [-1.26418478,  5.50847458,  3.4       ,  0.2       ],
       [-1.26418478,  5.33898305,  3.        ,  0.1       ],
       [-1.87002413,  5.08474576,  3.        ,  0.1       ],
       [-0.05250608,  5.16949153,  4.        ,  0.2       ],
       [-0.17367395,  5.42372881,  4.4       ,  0.4       ],
       [-0.53717756,  5.

In [19]:
ct0= ColumnTransformer([('std',StandardScaler(),[0]), ('norm', Normalizer(), [1]), ('minmax',MinMaxScaler(feature_range=(5,10)),[2])], remainder="passthrough")
ct0.fit(iris.data)
res_ct0=ct0.transform(iris.data)

res_ct0

array([[-0.90068117,  1.        ,  5.33898305,  0.2       ],
       [-1.14301691,  1.        ,  5.33898305,  0.2       ],
       [-1.38535265,  1.        ,  5.25423729,  0.2       ],
       [-1.50652052,  1.        ,  5.42372881,  0.2       ],
       [-1.02184904,  1.        ,  5.33898305,  0.2       ],
       [-0.53717756,  1.        ,  5.59322034,  0.4       ],
       [-1.50652052,  1.        ,  5.33898305,  0.3       ],
       [-1.02184904,  1.        ,  5.42372881,  0.2       ],
       [-1.74885626,  1.        ,  5.33898305,  0.2       ],
       [-1.14301691,  1.        ,  5.42372881,  0.1       ],
       [-0.53717756,  1.        ,  5.42372881,  0.2       ],
       [-1.26418478,  1.        ,  5.50847458,  0.2       ],
       [-1.26418478,  1.        ,  5.33898305,  0.1       ],
       [-1.87002413,  1.        ,  5.08474576,  0.1       ],
       [-0.05250608,  1.        ,  5.16949153,  0.2       ],
       [-0.17367395,  1.        ,  5.42372881,  0.4       ],
       [-0.53717756,  1.

In [7]:
ct2= ColumnTransformer([], remainder="passthrough")

ct2.transformers.append(('std',StandardScaler(),[0]))

print(type(ct2.transformers))
print(ct2)

ct2.fit(iris.data)
res_ct2=ct2.transform(iris.data)

res_ct2

<class 'list'>
ColumnTransformer(remainder='passthrough',
                  transformers=[('std', StandardScaler(), [0])])


array([[-0.90068117,  3.5       ,  1.4       ,  0.2       ],
       [-1.14301691,  3.        ,  1.4       ,  0.2       ],
       [-1.38535265,  3.2       ,  1.3       ,  0.2       ],
       [-1.50652052,  3.1       ,  1.5       ,  0.2       ],
       [-1.02184904,  3.6       ,  1.4       ,  0.2       ],
       [-0.53717756,  3.9       ,  1.7       ,  0.4       ],
       [-1.50652052,  3.4       ,  1.4       ,  0.3       ],
       [-1.02184904,  3.4       ,  1.5       ,  0.2       ],
       [-1.74885626,  2.9       ,  1.4       ,  0.2       ],
       [-1.14301691,  3.1       ,  1.5       ,  0.1       ],
       [-0.53717756,  3.7       ,  1.5       ,  0.2       ],
       [-1.26418478,  3.4       ,  1.6       ,  0.2       ],
       [-1.26418478,  3.        ,  1.4       ,  0.1       ],
       [-1.87002413,  3.        ,  1.1       ,  0.1       ],
       [-0.05250608,  4.        ,  1.2       ,  0.2       ],
       [-0.17367395,  4.4       ,  1.5       ,  0.4       ],
       [-0.53717756,  3.

In [8]:
pipe2=Pipeline([('ct',ct)])
print(pipe2.steps)
pipe2.steps.append(['bin', Binarizer()])
print(pipe2.steps)

pipe2.fit(iris.data)
res_pipe2=pipe2.transform(iris.data)
res_pipe2

[('ct', ColumnTransformer(remainder='passthrough',
                  transformers=[('std', StandardScaler(), [0]),
                                ('minmax', MinMaxScaler(feature_range=(5, 10)),
                                 [2])]))]
[('ct', ColumnTransformer(remainder='passthrough',
                  transformers=[('std', StandardScaler(), [0]),
                                ('minmax', MinMaxScaler(feature_range=(5, 10)),
                                 [2])])), ['bin', Binarizer()]]


array([[0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],
       [0., 1., 1., 1.],


In [9]:
from sklearn.decomposition import PCA
import numpy as np
pipe3=Pipeline([('std',StandardScaler()),('pca',PCA(n_components=3))])

pipe3.fit(iris.data)
res_pipe3=pipe3.transform(iris.data)
res_pipe3


array([[-2.26470281,  0.4800266 , -0.12770602],
       [-2.08096115, -0.67413356, -0.23460885],
       [-2.36422905, -0.34190802,  0.04420148],
       [-2.29938422, -0.59739451,  0.09129011],
       [-2.38984217,  0.64683538,  0.0157382 ],
       [-2.07563095,  1.48917752,  0.02696829],
       [-2.44402884,  0.0476442 ,  0.3354704 ],
       [-2.23284716,  0.22314807, -0.0886955 ],
       [-2.33464048, -1.11532768,  0.14507686],
       [-2.18432817, -0.46901356, -0.25376557],
       [-2.1663101 ,  1.04369065, -0.2686811 ],
       [-2.32613087,  0.13307834,  0.09375924],
       [-2.2184509 , -0.72867617, -0.23091124],
       [-2.6331007 , -0.96150673,  0.18079608],
       [-2.1987406 ,  1.86005711, -0.472901  ],
       [-2.26221453,  2.68628449,  0.03052661],
       [-2.2075877 ,  1.48360936, -0.00534409],
       [-2.19034951,  0.48883832, -0.04421532],
       [-1.898572  ,  1.40501879, -0.37434327],
       [-2.34336905,  1.12784938,  0.13263047],
       [-1.914323  ,  0.40885571, -0.421

In [10]:
np.var(res_pipe3,axis=0)

array([2.91849782, 0.91403047, 0.14675688])

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier 
X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.2,random_state=0)

pipe4=Pipeline([('std',StandardScaler()),('pca',PCA(n_components=3)),('tree',DecisionTreeClassifier())])

pipe4.fit(X_train,y_train)
res=pipe4.predict(X_train)
np.transpose(np.array([y_train,res]))




array([[2, 2],
       [1, 1],
       [0, 0],
       [2, 2],
       [2, 2],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [2, 2],
       [0, 0],
       [2, 2],
       [0, 0],
       [0, 0],
       [1, 1],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [1, 1],
       [2, 2],
       [1, 1],
       [1, 1],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [1, 1],
       [2, 2],
       [1, 1],
       [0, 0],
       [2, 2],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [2, 2],
       [0, 0],
       [0, 0],
       [2, 2],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [2, 2],
       [1, 1],
       [0, 0],
       [1, 1],
       [2, 2],
       [1, 1],
       [0, 0],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [0, 0],
       [0, 0],
       [2, 2],
       [2, 2],
       [0, 0],
       [2, 2],
       [0, 0],
       [2, 2],
       [2, 2],
       [0,

In [12]:
pipe4.score(X_test,y_test)

0.9666666666666667

In [13]:
pipe4.set_params(pca__n_components=4)
pipe4.fit(X_train,y_train)
pipe4.score(X_test,y_test)

1.0

In [14]:
from sklearn.model_selection import cross_val_score
scores=cross_val_score(pipe4,X_train,y_train,cv=10)

In [15]:
print(f"Średnia {scores.mean()}, odchylenie standardowe {scores.std()}")

Średnia 0.9166666666666666, odchylenie standardowe 0.07453559924999298
