In [1]:
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import numpy as np
from openpyxl import load_workbook
from openpyxl.utils.dataframe import dataframe_to_rows
import pandas as pd

In [2]:
header_column = 0
cols = "A:B"

wb = pd.read_excel('web_app\\documents\\user_1\\Zeszyt2.xlsx', header=header_column, usecols=cols)
print(wb)
print(type(wb))

FileNotFoundError: [Errno 2] No such file or directory: 'web_app\\documents\\user_1\\Zeszyt2.xlsx'

In [ ]:
# wb = load_workbook(filename = 'web_app\\documents\\user_1\\iris2.xlsx')
# ws = wb.active
# # print(wb.path)
# print(ws)
# df = pd.DataFrame(ws.values)
# print(df)

In [ ]:
from sklearn.compose import ColumnTransformer

ct= ColumnTransformer([('std',StandardScaler(),[0]), ('std2',StandardScaler(),[1])], remainder="passthrough")

ct.fit(wb)
res_ct=ct.transform(wb)

res_ct

array([[-1.67332005, -0.38913705],
       [-1.55379719, -0.39009837],
       [-1.43427433, -0.33241898],
       [-1.31475147, -0.37952382],
       [-1.19522861, -0.3458775 ],
       [-1.07570575, -0.08151359],
       [-0.95618289, -0.3747172 ],
       [-0.83666003, -0.36125868],
       [-0.71713717, -0.33145765],
       [-0.5976143 , -0.38336911],
       [-0.47809144, -0.36125868],
       [-0.35856858,  0.13478416],
       [-0.23904572,  4.57032998],
       [-0.11952286, -0.38336911],
       [ 0.        ,  1.67770809],
       [ 0.11952286, -0.39394367],
       [ 0.23904572,  1.19704643],
       [ 0.35856858, -0.33626427],
       [ 0.47809144, -0.38433044],
       [ 0.5976143 , -0.39394367],
       [ 0.71713717, -0.30934722],
       [ 0.83666003, -0.39394367],
       [ 0.95618289,  0.86731253],
       [ 1.07570575, -0.39394367],
       [ 1.19522861, -0.36510397],
       [ 1.31475147, -0.19110445],
       [ 1.43427433, -0.38433044],
       [ 1.55379719, -0.39394367],
       [ 1.67332005,

In [ ]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier 
X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.2,random_state=0)

pipe4=Pipeline([('std',StandardScaler()),('pca',PCA(n_components=4)),('tree',DecisionTreeClassifier())])

pipe4.fit(X_train,y_train)
res=pipe4.predict(X_train)
np.transpose(np.array([y_train,res]))




TypeError: LinearRegression.fit() missing 1 required positional argument: 'y'

In [ ]:
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])
scaler = preprocessing.StandardScaler().fit(X_train)
scaler

StandardScaler()

In [ ]:
scaler.mean_

array([1.        , 0.        , 0.33333333])

In [ ]:
scaler.scale_

array([0.81649658, 0.81649658, 1.24721913])

In [ ]:

X_scaled = scaler.transform(X_train)
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state=0)
X = [[ 1,  2,  3],  # 2 samples, 3 features
     [11, 12, 13]]
y = [0, 1]  # classes of each sample
clf.fit(X, y)
clf.predict(X)  # predict classes of the training data
clf.predict([[4, 5, 6], [14, 15, 16]])  # predict classes of new data

array([0, 1])

## Pickle

In [ ]:
import pickle

athletes = {
    "Name": ["Cristiano Ronaldo", "Lionel Messi", "Eden Hazard", "Luis Suarez", "Neymar"],
    "Club": ["Manchester United", "PSG", "Real Madrid", "Atletico Madrid", "PSG"]
 }

print(athletes)

{'Name': ['Cristiano Ronaldo', 'Lionel Messi', 'Eden Hazard', 'Luis Suarez', 'Neymar'], 'Club': ['Manchester United', 'PSG', 'Real Madrid', 'Atletico Madrid', 'PSG']}


In [ ]:
athletes_file = open('athletes.txt', 'wb')
pickle.dump(athletes, athletes_file)
athletes_file.close()

In [ ]:
athletes_file = open("athletes.txt", "rb")
athletes = pickle.load(athletes_file)
athletes_file.close()
print(athletes)

{'Name': ['Cristiano Ronaldo', 'Lionel Messi', 'Eden Hazard', 'Luis Suarez', 'Neymar'], 'Club': ['Manchester United', 'PSG', 'Real Madrid', 'Atletico Madrid', 'PSG']}


## List my_pipeline

In [ ]:
my_dict = {'StandardScaler': StandardScaler(), 'MinMaxScaler': MinMaxScaler()}

In [ ]:
my_pipeline = list()
my_pipeline.append(['std','StandardScaler',[0]])
my_pipeline.append(['minmax','MinMaxScaler',[1]])
my_pipeline.append(['minmax','MinMaxScaler',[0]])

pipe = my_pipeline.copy()
print(f'Pipe: {pipe}')
print('StandardScaler' in pipe[0])
# print(len(pipe))
# pipe[0] = tuple(pipe[0])
print(len(pipe))
print(type(pipe[0]))


Pipe: [['std', 'StandardScaler', [0]], ['minmax', 'MinMaxScaler', [1]], ['minmax', 'MinMaxScaler', [0]]]
True
3
<class 'list'>


In [ ]:
for i in range(len(pipe)):
    print(i)
    if 'StandardScaler' in pipe[i]:
        n_index = pipe[i].index('StandardScaler')
        # print(f'n_index: {n_index}')
        std = my_dict['StandardScaler']
        # print(f'std: {std}')
        pipe[i][n_index] = my_dict['StandardScaler']
        # print(pipe)
        pipe[i] = tuple(pipe[i])
    elif 'MinMaxScaler' in pipe[i]:
        n_index = pipe[i].index('MinMaxScaler')
        # print(f'n_index: {n_index}')
        std = my_dict['MinMaxScaler']
        # print(f'std: {std}')
        pipe[i][n_index] = my_dict['MinMaxScaler']
        # print(pipe)
        pipe[i] = tuple(pipe[i])
print(pipe)

0
1
2
[('std', StandardScaler(), [0]), ('minmax', MinMaxScaler(), [1]), ('minmax', MinMaxScaler(), [0])]


In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm

X, y = datasets.load_iris(return_X_y=True)
X.shape, y.shape

((150, 4), (150,))

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.4, random_state=0)

X_train.shape, y_train.shape
X_test.shape, y_test.shape

clf = svm.SVC(kernel='linear', C=1).fit(X_train, y_train)
clf.score(X_test, y_test)

0.9666666666666667

In [ ]:
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='linear', C=1, random_state=42)
scores = cross_val_score(clf, X, y, cv=5)
scores

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

## Instrukcja wykorzystania modelu

In [8]:
# zaimportuj potrzebne paczki
import pandas as pd
from sklearn import metrics
import pickle

# zaimportuj zbiór danych dla których chcesz zastosować model
dataset = pd.read_excel('web_app//documents//user_1//data//linear2.xlsx') 

X = dataset.iloc[:, : -1].values 
Y = dataset.iloc[:, -1].values 

print(X)

# załaduj model
with open('web_app//documents//user_1//models//linear_model_test.pickle', 'rb') as f:
    load_model = pickle.load(f)

y_pred = load_model.predict(X)
print('root mean squared error : ', metrics.r2_score(Y, y_pred)) 


[[  1   2]
 [  2   6]
 [  3  10]
 [  4  14]
 [  5  18]
 [  6  22]
 [  7  26]
 [  8  30]
 [  9  34]
 [ 10  38]
 [ 11  42]
 [ 12  46]
 [ 13  50]
 [ 14  54]
 [ 15  58]
 [ 16  62]
 [ 17  66]
 [ 18  70]
 [ 19  74]
 [ 20  78]
 [ 21  82]
 [ 22  86]
 [ 23  90]
 [ 24  94]
 [ 25  98]
 [ 26 102]
 [ 27 106]
 [ 28 110]
 [ 29 114]
 [ 30 118]
 [ 31 122]
 [ 32 126]
 [ 33 130]
 [ 34 134]
 [ 35 138]
 [ 36 142]
 [ 37 146]
 [ 38 150]
 [ 39 154]
 [ 40 158]
 [ 41 162]
 [ 42 166]
 [ 43 170]
 [ 44 174]
 [ 45 178]
 [ 46 182]
 [ 47 186]
 [ 48 190]
 [ 49 194]
 [ 50 198]
 [ 51 202]
 [ 52 206]
 [ 53 210]
 [ 54 214]
 [ 55 218]
 [ 56 222]
 [ 57 226]
 [ 58 230]
 [ 59 234]
 [ 60 238]
 [ 61 242]
 [ 62 246]
 [ 63 250]
 [ 64 254]
 [ 65 258]
 [ 66 262]
 [ 67 266]
 [ 68 270]
 [ 69 274]
 [ 70 278]
 [ 71 282]
 [ 72 286]
 [ 73 290]
 [ 74 294]
 [ 75 298]
 [ 76 302]
 [ 77 306]
 [ 78 310]
 [ 79 314]
 [ 80 318]
 [ 81 322]
 [ 82 326]
 [ 83 330]
 [ 84 334]
 [ 85 338]
 [ 86 342]
 [ 87 346]
 [ 88 350]
 [ 89 354]
 [ 90 358]
 [ 91 362]

c:\.STUDIA\thesis\.venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


In [1]:
max_c = [1, 2]

[x for x in range(len(max_c))]

[0, 1]