In [1]:
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import numpy as np
from openpyxl import load_workbook
from openpyxl.utils.dataframe import dataframe_to_rows
import pandas as pd

In [2]:
header_column = 0
cols = "A:B"

wb = pd.read_excel('web_app\\documents\\user_1\\Zeszyt2.xlsx', header=header_column, usecols=cols)
print(wb)
print(type(wb))

FileNotFoundError: [Errno 2] No such file or directory: 'web_app\\documents\\user_1\\Zeszyt2.xlsx'

In [ ]:
# wb = load_workbook(filename = 'web_app\\documents\\user_1\\iris2.xlsx')
# ws = wb.active
# # print(wb.path)
# print(ws)
# df = pd.DataFrame(ws.values)
# print(df)

In [ ]:
from sklearn.compose import ColumnTransformer

ct= ColumnTransformer([('std',StandardScaler(),[0]), ('std2',StandardScaler(),[1])], remainder="passthrough")

ct.fit(wb)
res_ct=ct.transform(wb)

res_ct

array([[-1.67332005, -0.38913705],
       [-1.55379719, -0.39009837],
       [-1.43427433, -0.33241898],
       [-1.31475147, -0.37952382],
       [-1.19522861, -0.3458775 ],
       [-1.07570575, -0.08151359],
       [-0.95618289, -0.3747172 ],
       [-0.83666003, -0.36125868],
       [-0.71713717, -0.33145765],
       [-0.5976143 , -0.38336911],
       [-0.47809144, -0.36125868],
       [-0.35856858,  0.13478416],
       [-0.23904572,  4.57032998],
       [-0.11952286, -0.38336911],
       [ 0.        ,  1.67770809],
       [ 0.11952286, -0.39394367],
       [ 0.23904572,  1.19704643],
       [ 0.35856858, -0.33626427],
       [ 0.47809144, -0.38433044],
       [ 0.5976143 , -0.39394367],
       [ 0.71713717, -0.30934722],
       [ 0.83666003, -0.39394367],
       [ 0.95618289,  0.86731253],
       [ 1.07570575, -0.39394367],
       [ 1.19522861, -0.36510397],
       [ 1.31475147, -0.19110445],
       [ 1.43427433, -0.38433044],
       [ 1.55379719, -0.39394367],
       [ 1.67332005,

In [ ]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier 
X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.2,random_state=0)

pipe4=Pipeline([('std',StandardScaler()),('pca',PCA(n_components=4)),('tree',DecisionTreeClassifier())])

pipe4.fit(X_train,y_train)
res=pipe4.predict(X_train)
np.transpose(np.array([y_train,res]))




TypeError: LinearRegression.fit() missing 1 required positional argument: 'y'

In [ ]:
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])
scaler = preprocessing.StandardScaler().fit(X_train)
scaler

StandardScaler()

In [ ]:
scaler.mean_

array([1.        , 0.        , 0.33333333])

In [ ]:
scaler.scale_

array([0.81649658, 0.81649658, 1.24721913])

In [ ]:

X_scaled = scaler.transform(X_train)
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state=0)
X = [[ 1,  2,  3],  # 2 samples, 3 features
     [11, 12, 13]]
y = [0, 1]  # classes of each sample
clf.fit(X, y)
clf.predict(X)  # predict classes of the training data
clf.predict([[4, 5, 6], [14, 15, 16]])  # predict classes of new data

array([0, 1])

## Pickle

In [ ]:
import pickle

athletes = {
    "Name": ["Cristiano Ronaldo", "Lionel Messi", "Eden Hazard", "Luis Suarez", "Neymar"],
    "Club": ["Manchester United", "PSG", "Real Madrid", "Atletico Madrid", "PSG"]
 }

print(athletes)

{'Name': ['Cristiano Ronaldo', 'Lionel Messi', 'Eden Hazard', 'Luis Suarez', 'Neymar'], 'Club': ['Manchester United', 'PSG', 'Real Madrid', 'Atletico Madrid', 'PSG']}


In [ ]:
athletes_file = open('athletes.txt', 'wb')
pickle.dump(athletes, athletes_file)
athletes_file.close()

In [ ]:
athletes_file = open("athletes.txt", "rb")
athletes = pickle.load(athletes_file)
athletes_file.close()
print(athletes)

{'Name': ['Cristiano Ronaldo', 'Lionel Messi', 'Eden Hazard', 'Luis Suarez', 'Neymar'], 'Club': ['Manchester United', 'PSG', 'Real Madrid', 'Atletico Madrid', 'PSG']}


## List my_pipeline

In [ ]:
my_dict = {'StandardScaler': StandardScaler(), 'MinMaxScaler': MinMaxScaler()}

In [ ]:
my_pipeline = list()
my_pipeline.append(['std','StandardScaler',[0]])
my_pipeline.append(['minmax','MinMaxScaler',[1]])
my_pipeline.append(['minmax','MinMaxScaler',[0]])

pipe = my_pipeline.copy()
print(f'Pipe: {pipe}')
print('StandardScaler' in pipe[0])
# print(len(pipe))
# pipe[0] = tuple(pipe[0])
print(len(pipe))
print(type(pipe[0]))


Pipe: [['std', 'StandardScaler', [0]], ['minmax', 'MinMaxScaler', [1]], ['minmax', 'MinMaxScaler', [0]]]
True
3
<class 'list'>


In [ ]:
for i in range(len(pipe)):
    print(i)
    if 'StandardScaler' in pipe[i]:
        n_index = pipe[i].index('StandardScaler')
        # print(f'n_index: {n_index}')
        std = my_dict['StandardScaler']
        # print(f'std: {std}')
        pipe[i][n_index] = my_dict['StandardScaler']
        # print(pipe)
        pipe[i] = tuple(pipe[i])
    elif 'MinMaxScaler' in pipe[i]:
        n_index = pipe[i].index('MinMaxScaler')
        # print(f'n_index: {n_index}')
        std = my_dict['MinMaxScaler']
        # print(f'std: {std}')
        pipe[i][n_index] = my_dict['MinMaxScaler']
        # print(pipe)
        pipe[i] = tuple(pipe[i])
print(pipe)

0
1
2
[('std', StandardScaler(), [0]), ('minmax', MinMaxScaler(), [1]), ('minmax', MinMaxScaler(), [0])]


In [3]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm

X, y = datasets.load_iris(return_X_y=True)
X.shape, y.shape

((150, 4), (150,))

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.4, random_state=0)

X_train.shape, y_train.shape
X_test.shape, y_test.shape

clf = svm.SVC(kernel='linear', C=1).fit(X_train, y_train)
clf.score(X_test, y_test)

0.9666666666666667

In [5]:
from sklearn.model_selection import cross_val_score
clf = svm.SVC(kernel='linear', C=1, random_state=42)
scores = cross_val_score(clf, X, y, cv=5)
scores

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])