In [10]:
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import numpy as np
from openpyxl import load_workbook
from openpyxl.utils.dataframe import dataframe_to_rows
import pandas as pd

In [8]:
header_column = 1
cols = "B:E"

wb = pd.read_excel('web_app\\documents\\user_1\\iris.xlsx', header=header_column, usecols=cols)
print(wb)

FileNotFoundError: [Errno 2] No such file or directory: 'web_app\\documents\\user_1\\iris.xlsx'

In [ ]:
wb = load_workbook(filename = 'web_app\\documents\\user_1\\iris.xlsx')
ws = wb.active
# print(wb.path)
print(ws)
df = pd.DataFrame(ws.values)
print(df)

<Worksheet "Sheet1">
       0                  1                 2                  3   \
0    None               None              None               None   
1    None  Sepal Length (cm)  Sepal Width (cm)  Petal Length (cm)   
2    None                  7               3.2                4.7   
3    None                6.4               3.2                4.5   
4    None                6.9               3.1                4.9   
..    ...                ...               ...                ...   
97   None                4.8                 3                1.4   
98   None                5.1               3.8                1.6   
99   None                4.6               3.2                1.4   
100  None                5.3               3.7                1.5   
101  None                  5               3.3                1.4   

                   4                5     6    7      8   \
0                None             None  None  NaN   None   
1    Petal Width (cm)         

In [ ]:
from sklearn.compose import ColumnTransformer

ct= ColumnTransformer([('std',StandardScaler(),[0])], remainder="passthrough")

ct.fit(df)
res_ct=ct.transform(df)

res_ct

c:\.STUDIA\thesis\.venv\Lib\site-packages\sklearn\utils\extmath.py:1050: RuntimeWarning: invalid value encountered in divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
c:\.STUDIA\thesis\.venv\Lib\site-packages\sklearn\utils\extmath.py:1055: RuntimeWarning: invalid value encountered in divide
  T = new_sum / new_sample_count
c:\.STUDIA\thesis\.venv\Lib\site-packages\sklearn\utils\extmath.py:1075: RuntimeWarning: invalid value encountered in divide
  new_unnormalized_variance -= correction**2 / new_sample_count


array([[nan, None, None, ..., None, nan, None],
       [nan, 'Sepal Length (cm)', 'Sepal Width (cm)', ..., 'obj', nan,
        None],
       [nan, 7, 3.2, ..., '=SUM(delta_plus) + SUM(delta_minus)', 0.0,
       ...,
       [nan, 4.6, 3.2, ..., None, 0.0, 1],
       [nan, 5.3, 3.7, ..., None, 0.0, 1],
       [nan, 5, 3.3, ..., None, 0.0, 1]], dtype=object)

In [ ]:
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])
scaler = preprocessing.StandardScaler().fit(X_train)
scaler

StandardScaler()

In [ ]:
scaler.mean_

array([1.        , 0.        , 0.33333333])

In [ ]:
scaler.scale_

array([0.81649658, 0.81649658, 1.24721913])

In [ ]:

X_scaled = scaler.transform(X_train)
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

## Pickle

In [ ]:
import pickle

athletes = {
    "Name": ["Cristiano Ronaldo", "Lionel Messi", "Eden Hazard", "Luis Suarez", "Neymar"],
    "Club": ["Manchester United", "PSG", "Real Madrid", "Atletico Madrid", "PSG"]
 }

print(athletes)

{'Name': ['Cristiano Ronaldo', 'Lionel Messi', 'Eden Hazard', 'Luis Suarez', 'Neymar'], 'Club': ['Manchester United', 'PSG', 'Real Madrid', 'Atletico Madrid', 'PSG']}


In [ ]:
athletes_file = open('athletes.txt', 'wb')
pickle.dump(athletes, athletes_file)
athletes_file.close()

In [ ]:
athletes_file = open("athletes.txt", "rb")
athletes = pickle.load(athletes_file)
athletes_file.close()
print(athletes)

{'Name': ['Cristiano Ronaldo', 'Lionel Messi', 'Eden Hazard', 'Luis Suarez', 'Neymar'], 'Club': ['Manchester United', 'PSG', 'Real Madrid', 'Atletico Madrid', 'PSG']}


## List my_pipeline

In [11]:
my_dict = {'StandardScaler': StandardScaler(), 'MinMaxScaler': MinMaxScaler()}

In [43]:
my_pipeline = list()
my_pipeline.append(['std','StandardScaler',[0]])
my_pipeline.append(['minmax','MinMaxScaler',[1]])
my_pipeline.append(['minmax','MinMaxScaler',[0]])

pipe = my_pipeline.copy()
print(f'Pipe: {pipe}')
print('StandardScaler' in pipe[0])
# print(len(pipe))
# pipe[0] = tuple(pipe[0])
print(len(pipe))
print(type(pipe[0]))


Pipe: [['std', 'StandardScaler', [0]], ['minmax', 'MinMaxScaler', [1]], ['minmax', 'MinMaxScaler', [0]]]
True
3
<class 'list'>


In [45]:
for i in range(len(pipe)):
    print(i)
    if 'StandardScaler' in pipe[i]:
        n_index = pipe[i].index('StandardScaler')
        # print(f'n_index: {n_index}')
        std = my_dict['StandardScaler']
        # print(f'std: {std}')
        pipe[i][n_index] = my_dict['StandardScaler']
        # print(pipe)
        pipe[i] = tuple(pipe[i])
    elif 'MinMaxScaler' in pipe[i]:
        n_index = pipe[i].index('MinMaxScaler')
        # print(f'n_index: {n_index}')
        std = my_dict['MinMaxScaler']
        # print(f'std: {std}')
        pipe[i][n_index] = my_dict['MinMaxScaler']
        # print(pipe)
        pipe[i] = tuple(pipe[i])
print(pipe)

0
1
2
[('std', StandardScaler(), [0]), ('minmax', MinMaxScaler(), [1]), ('minmax', MinMaxScaler(), [0])]
